name: 友链模板
about: 自助添加友链。请遵守 JSON 格式，在双引号中填写。
description: 自助添加友链。请遵守 JSON 格式，在双引号中填写。
title: '友链：'
labels: []
body:
  - type: input
    id: friends-html
    attributes:
      label: 我的友链地址
      description: 请输入您的友链页面地址。
      placeholder: "如: https://xaoxuu.com/friends/"
    validations:
      required: true
  - type: textarea
    id: config-file
    validations:
      required: true
    attributes:
      label: 配置文件
      description: 请在双引号中填写，不要修改格式。
      value: |
        ```json
        {
            "title": "",
            "url": "",
            "avatar": "",
            "screenshot": "",
            "description": ""
        }
        ```
  - type: input
    id: friends-repo
    attributes:
      label: 我的友链仓库（可选）
      description: 如果您使用 issue 作为友链源，请附上 issue 仓库链接，否则请直接添加 xaoxuu.com 到您的友链中。
      placeholder: "如: https://github.com/xaoxuu/friends/"
